version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: POSTGRES-DB
      POSTGRES_USER: POSTGRES-USER
      POSTGRES_PASSWORD: POSTGRES-PASSWORD
    ports:
      - "5432:5432"
    networks:
      - bot_dev
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    command: bash -c "redis-server --requirepass REDIS-PASSWORD"
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - redis:/resources
    networks:
      - bot_dev

  bot:
    build: ./
    container_name: bot
    restart: always
    depends_on:
      - redis
      - postgres
    networks:
      - bot_dev

volumes:
  database:
  redis:

networks:
  bot_dev:
    external: true